site_name: Heqing's Blog
theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

plugins:
  - blog:
      blog_dir: blog
  - search:
nav:
  - Home: index.md
  - Blog:
    - "blog/index.md"
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh


