site_name: Heqing's Blog
site_url: https://heqing.me/zh
theme:
  name: material
  language: zh
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

plugins:
  - blog:
      blog_dir: blog
      post_url_format: "{date}/{file}"
  - search:
nav:
  - 关于我: index.md
  - 博客:
    - "blog/index.md"
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh


